apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-homelab-sacenpapier
  namespace: homelab-dashboard
spec:
  tokenSecret:
    name: doppler-token-homelab-sacenpapier
  project: homelab-sacenpapier
  config: prd
  secrets:
    - TRUENAS_API_KEY
    - K3S_BEARER_TOKEN
  managedSecret:
    name: homelab-backend-secrets
    namespace: homelab-dashboard
    type: Opaque
